// SPDX-License-Identifier: MIT OR Apache-2.0
//! Claim a board, put the right image on it, and capture what it says.
//!
//! ```text
//! m5stack-hil --board <NAME> --ensure-image <ELF> --capture 20
//! m5stack-hil --board <NAME> --read-identity
//! m5stack-hil --mac <MAC> --await-boot 'wifi: got ip'
//! ```
//!
//! The full synopsis is `--help`, generated by `clap` from [`Cli`] so it cannot
//! drift — which a hand-maintained usage string in this comment did.
//!
//! `--board` resolves through `hil.toml`, because a MAC is a fact about **a
//! rig**, not about a command line; `--mac` and `--port`/`--id` remain for
//! one-off use with no config. It owns what a script gets wrong — claiming the
//! board, holding the port, keeping every byte, deciding when a wait is over —
//! and delegates what existing tools do well: `espflash`, `probe-rs`,
//! `sha256sum`, `stty`.
//!
//! Reading the identity needs a reset **we** caused: the line goes out in the
//! first fraction of a second, so a board that booted an hour ago cannot be
//! asked. That is also why asking (~6 s) can replace flashing (~15 s).
//!
//! Resetting a board with **no** probe is the one job not delegated: every
//! external tool for it needs the port to itself, and letting go across a reset
//! means re-opening into a boot already under way. See
//! [`m5stack_core_hil::board::Reset::SerialLines`].

use std::{fs, path::PathBuf, process::ExitCode, time::Duration};

use clap::{ArgGroup, Args, Parser};
use m5stack_core_hil::{
    board::{self, Board, Capture},
    config::Config,
    flash::{self, Ensured, FlashConfig},
    listen::{Listener, Outcome},
    lock::BoardLock,
    serial::DrainedSource,
};

/// How many hex characters of the content hash are compared.
///
/// Must match what `m5stack-core`'s console prints (6 bytes). Read back off the
/// board's own line where one is available, so this is only the fallback used
/// when computing what an ELF *should* report.
const HASH_PREFIX_LEN: usize = 12;

/// A pattern that cannot occur in board output, for a capture that is bounded
/// only by its deadline. Using the normal wait path rather than a second
/// read loop keeps streaming, buffering and the deadline in one place.
const NEVER: &str = "\u{0}m5stack-hil:no-such-pattern";

/// Where the board is, and how to look it up.
///
/// Its own type because these flags constrain *each other*, and a rule stays
/// true most reliably when it sits with the fields it governs — hence the
/// `ArgGroup` here rather than on [`Cli`].
#[derive(Debug, Args)]
#[command(group(ArgGroup::new("address").required(true).args(["board", "mac", "port"])))]
struct AddressArgs {
    /// Board to use, by name in hil.toml
    #[arg(long)]
    board: Option<String>,

    // A doc comment here would become `--help` text, so this is an ordinary
    // one: `conflicts_with_all`, NOT `requires = "board"`. `requires` does not
    // fire when the required argument is in an already-satisfied
    // `required(true)` group — so `--rig bench --mac AA:BB` parsed cleanly and
    // then ignored `--rig`, which is exactly the silent-ignore this conversion
    // exists to remove. Found by running it, not by reading the docs. Stating
    // the conflict is the truer sentence anyway: a rig only means anything when
    // a config is being consulted.
    /// Rig to look that board up in; defaults to the config's `default_rig`
    #[arg(long, conflicts_with_all = ["mac", "port"])]
    rig: Option<String>,

    /// Config file to read, instead of discovering hil.toml
    #[arg(long, value_name = "PATH", conflicts_with_all = ["mac", "port"])]
    config: Option<PathBuf>,

    /// Address a CoreS3 directly by MAC, with no config file
    #[arg(long)]
    mac: Option<String>,

    /// Address a board directly by device path
    #[arg(long, value_name = "PATH", requires = "id")]
    port: Option<String>,

    /// Stable lock key for --port: a MAC or adapter serial, never a tty index
    #[arg(long)]
    id: Option<String>,

    /// Console baud rate
    #[arg(long)]
    baud: Option<u32>,
}

impl AddressArgs {
    /// The board, the flash settings its config knows about, and its banner.
    ///
    /// # Errors
    /// If the config cannot be read, or does not define the board.
    fn resolve(&self) -> Result<(Board, FlashConfig, Option<String>), String> {
        let (mut board, flash, banner) = if let Some(name) = &self.board {
            let (path, conf) = self.load_config(name)?;
            let entry = conf.board(self.rig.as_deref(), name).map_err(|e| format!("{}: {e}", path.display()))?;
            (entry.to_board()?, entry.to_flash_config(), entry.banner.clone())
        } else if let Some(mac) = &self.mac {
            (Board::cores3(mac), FlashConfig::cores3(), None)
        } else if let Some(port) = &self.port {
            // A lock keyed to a tty index would let two runs claim one board
            // under two names, so an explicit port needs an explicit stable id.
            // `requires = "id"` is what enforces that; this states the same fact
            // for a reader rather than trusting the attribute alone.
            let id = self.id.clone().ok_or_else(|| "--port needs --id <stable-id>".to_string())?;
            (Board::at_port(&id, port, self.baud.unwrap_or(1_000_000)), FlashConfig::cores3(), None)
        } else {
            // The `address` group is `required(true)`, so clap refuses long
            // before here. An error rather than a panic if that ever changes.
            return Err("no board addressed — --board, --mac or --port is required".into());
        };
        if let Some(n) = self.baud {
            board.baud = n;
        }
        Ok((board, flash, banner))
    }

    /// The config named by `--config`, or the first one discovered.
    ///
    /// # Errors
    /// If the named file cannot be read or parsed, or none is found.
    fn load_config(&self, name: &str) -> Result<(PathBuf, Config), String> {
        if let Some(p) = &self.config {
            let text = fs::read_to_string(p).map_err(|e| format!("{}: {e}", p.display()))?;
            return Ok((p.clone(), Config::parse(&text).map_err(|e| format!("{}: {e}", p.display()))?));
        }
        let here = std::env::current_dir().map_err(|e| format!("cannot read the working directory: {e}"))?;
        Config::discover(&here)?.ok_or_else(|| {
            format!(
                "--board {name} needs a config, and no {} was found here, in any parent \
                 directory, or at ~/.config/m5stack-hil/. Name one with --config or \
                 ${}, or address the board directly with --mac / --port.",
                m5stack_core_hil::config::FILE_NAME,
                m5stack_core_hil::config::ENV_VAR
            )
        })
    }
}

/// `espflash` settings, as overrides rather than as values.
///
/// Every field is `Option` because these arrive from three places, later
/// winning: the per-chip default, the board's `hil.toml` entry, then a flag.
/// Keeping them together with [`FlashArgs::over`] is what makes that ordering
/// one call at the use site instead of four `if let`s.
#[derive(Debug, Args)]
struct FlashArgs {
    /// espflash --chip
    #[arg(long)]
    chip: Option<String>,

    /// espflash --flash-size
    #[arg(long)]
    flash_size: Option<String>,

    /// espflash --flash-freq
    #[arg(long)]
    flash_freq: Option<String>,

    /// espflash --partition-table
    #[arg(long)]
    partition_table: Option<PathBuf>,
}

impl FlashArgs {
    /// Layer what was actually given over `base`, leaving the rest alone.
    ///
    /// `.or(base.x)` rather than a chain of `if let`s: "the flag if there is
    /// one, otherwise what was already there" is exactly what `Option::or`
    /// says, and saying it three times in three lines is harder to get subtly
    /// wrong than saying it three times in nine.
    fn over(&self, mut base: FlashConfig) -> FlashConfig {
        // Not `.or()` — `chip` is not optional in a `FlashConfig`, because
        // espflash always needs one.
        if let Some(v) = &self.chip {
            base.chip.clone_from(v);
        }
        base.flash_size = self.flash_size.clone().or(base.flash_size);
        base.flash_freq = self.flash_freq.clone().or(base.flash_freq);
        base.partition_table = self.partition_table.clone().or(base.partition_table);
        base
    }
}

/// The command line, declared rather than parsed.
///
/// Every rule that is a rule *about arguments* is an attribute enforced by
/// `clap`: which flags are alternatives, which imply which, which are required.
/// They used to be `if` chains after a hand-written match over `env::args()`,
/// which is the shape that lets a rule be *forgotten* — `--rig` alongside
/// `--mac`, and `--until` with no `--capture`, were both accepted and then
/// silently ignored, because nothing checked them.
///
/// What is deliberately NOT here is anything needing the filesystem: reading
/// `hil.toml`, and layering flash settings. That is [`Cli::resolve`], because a
/// parser cannot know it.
#[derive(Debug, Parser)]
#[command(
    name = "m5stack-hil",
    version,
    // Stated, not taken from the doc comment above: that comment explains a
    // design decision to whoever maintains this file, and `--help` is read by
    // somebody trying to drive a board. `long_about = None` stops clap using
    // the rest of it for `--help`.
    about = "Claim a board, put the right image on it, and capture what it says",
    long_about = None,
    // At least one action, any number of them. Without this the tool would
    // claim a board, reset it, and exit having proved nothing at all.
    group(
        ArgGroup::new("action")
            .required(true)
            .multiple(true)
            .args(["read_identity", "expect_image", "ensure_image", "await_boot", "capture"])
    )
)]
struct Cli {
    #[command(flatten)]
    address: AddressArgs,

    #[command(flatten)]
    flash: FlashArgs,

    /// Print the identity the board reports at boot, then exit
    #[arg(long)]
    read_identity: bool,

    /// Fail unless the board is already running this ELF
    #[arg(long, value_name = "ELF")]
    expect_image: Option<PathBuf>,

    /// Write this ELF, but only if the board is not already running it
    #[arg(long, value_name = "ELF")]
    ensure_image: Option<PathBuf>,

    /// Wait for this substring once the image is settled
    #[arg(long, value_name = "SUB")]
    await_boot: Option<String>,

    /// Capture for this many seconds
    #[arg(long, value_name = "SECS")]
    capture: Option<u64>,

    /// End the capture at this substring; not seeing it fails the run
    #[arg(long, value_name = "SUB", requires = "capture")]
    until: Option<String>,

    /// Substring the application prints before its identity line
    #[arg(long, value_name = "SUB")]
    banner: Option<String>,

    /// Directory for transcripts and lockfiles
    #[arg(long, value_name = "DIR", default_value = "work/hil")]
    out: PathBuf,
}

/// The three things a command line cannot state on its own: which board, what
/// to write to it, and what it says before its identity.
///
/// Deliberately not a mirror of [`Cli`]. The struct this replaced restated ten
/// fields verbatim and then copied them across one by one — twenty-five lines
/// of transcription to derive three values. Everything a run needs that the
/// user simply *typed* is read from `Cli` directly.
struct Target {
    board: Board,
    flash: FlashConfig,
    banner: Option<String>,
}

impl Cli {
    /// Settle the parts that need the filesystem: which board `hil.toml`
    /// means, and the flash settings layered over its per-chip defaults.
    ///
    /// # Errors
    /// If the board cannot be resolved — see [`AddressArgs::resolve`].
    fn resolve(&self) -> Result<Target, String> {
        let (board, base, config_banner) = self.address.resolve()?;
        // A board addressed by `--port` has no config entry to take flash
        // defaults from, so `--chip esp32` has to choose the base itself —
        // otherwise it would mean "an ESP32-S3's settings with the name
        // swapped". Naming a board in hil.toml already does this, and
        // addressing one directly must not behave differently.
        let base = match (&self.address.port, self.flash.chip.as_deref()) {
            (Some(_), Some(chip)) => FlashConfig::for_chip(chip),
            _ => base,
        };
        Ok(Target {
            board,
            flash: self.flash.over(base),
            // A `--banner` flag beats the board's config entry.
            banner: self.banner.clone().or(config_banner),
        })
    }
}

/// Progress, on the stream that will not corrupt a caller's capture.
///
/// `--read-identity` puts **one line on stdout** so a shell can use
/// `$(m5stack-hil --read-identity …)` directly. Progress printed with
/// `println!` would break that, and break it invisibly.
fn note(quiet: bool, msg: &str) {
    if quiet {
        eprintln!("{msg}");
    } else {
        println!("{msg}");
    }
}

fn main() -> ExitCode {
    // `parse` handles `--help`, `--version` and every malformed command line
    // itself, exiting with the conventional codes and writing help to stdout
    // but errors to stderr. That is a distinction the hand-written version got
    // wrong: it returned its usage text as an Err, so `--help` printed to
    // stderr and exited non-zero.
    let cli = Cli::parse();
    match run(&cli) {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("m5stack-hil: {e}");
            ExitCode::FAILURE
        }
    }
}

#[allow(clippy::too_many_lines, reason = "one linear procedure; splitting it would hide the order that matters")]
fn run(cli: &Cli) -> Result<(), String> {
    let target = cli.resolve()?;
    fs::create_dir_all(&cli.out).map_err(|e| format!("cannot create {}: {e}", cli.out.display()))?;

    // Claim the board BEFORE opening anything. A refusal names the live holder
    // and exits; it never reclaims.
    let lock = BoardLock::acquire(&cli.out.join("locks"), &target.board.id).map_err(|e| e.to_string())?;
    if lock.took_over_stale() {
        eprintln!("m5stack-hil: took over a stale lock — a previous run died without releasing");
    }

    let quiet = cli.read_identity;
    note(quiet, &format!("m5stack-hil: board {} -> {}", target.board.id, target.board.port));

    // ATTACH FIRST, RESET SECOND — the order is load-bearing.
    //
    // The board's USB-Serial-JTAG discards output when nobody is reading, and
    // the identity goes out at ~0.3 s of uptime. Opening after the reset
    // therefore misses it: measured, an attach-after-reset captured 0 bytes
    // from a board that was demonstrably printing. Attaching first means the
    // capture starts before the chip does.
    //
    // ONE listener for the whole run, streamed from the first byte rather than
    // written at the end: a run that dies is exactly the run whose transcript
    // matters.
    let cap = cli.out.join(format!("{}-transcript.log", target.board.id.replace(':', "-")));
    let sink = fs::File::create(&cap).map_err(|e| format!("cannot create {}: {e}", cap.display()))?;
    let port =
        DrainedSource::open(&target.board.port, target.board.baud).map_err(|e| format!("{}: {e}", target.board.port))?;
    let mut l = Listener::new(port).streaming_to(Box::new(sink));
    note(quiet, &format!("m5stack-hil: streaming transcript -> {}", cap.display()));

    // Every action here needs to see the boot, so the reset is unconditional:
    // the identity and any banner are printed once, early, and a reader that
    // attached at some other moment cannot see them and would have to guess.
    note(quiet, "m5stack-hil: resetting to catch bring-up from the start");
    // A chatty board cannot have its boots told apart, so `--until` could match
    // a line the PREVIOUS boot printed and call a run that never got there a
    // pass. Said out loud rather than left for the reader to deduce.
    if board::reset_attached(&target.board, &mut l)? == board::Isolation::Chatty {
        eprintln!(
            "m5stack-hil: WARNING — board {} never went quiet before the reset, so output from \
             the previous boot may still be matchable. A --until/--await-boot match may be stale.",
            target.board.id
        );
    }

    let wants_identity = cli.read_identity || cli.expect_image.is_some() || cli.ensure_image.is_some();
    if wants_identity {
        let capture = board::read_identity(&mut l, target.banner.as_deref(), board::IDENTITY_BUDGET)
            .map_err(|m| format!("{}: {m}", target.board.port))?;

        // "Never reached the application" is a hard stop for the modes that only
        // VERIFY — nothing was observed, so nothing can be checked. It is
        // emphatically NOT a stop for --ensure-image: a bad or erased image is
        // precisely what flashing repairs.
        if cli.read_identity || cli.expect_image.is_some() {
            board::no_holes(&l, &format!("board {}", target.board.id))?;
            if capture == Capture::NoApplication {
                return Err(format!(
                    "board {} never reached the application within {:?} of a reset.\n\
                     Nothing was observed, so nothing is proved — a bad image, a board held in the \
                     bootloader and a broken capture all look like this.\nTranscript: {}",
                    target.board.id,
                    board::IDENTITY_BUDGET,
                    cap.display()
                ));
            }
        }

        if cli.read_identity {
            let Capture::Identified(id) = &capture else {
                return Err(format!(
                    "board {} printed no identity within {:?} of a reset — an image built without \
                     `m5stack_core::app_desc!()`, or not booting.\nTranscript: {}",
                    target.board.id,
                    board::IDENTITY_BUDGET,
                    cap.display()
                ));
            };
            // One line on stdout so a shell can capture it directly.
            println!("{id}");
            return Ok(());
        }

        if let Some(elf) = &cli.expect_image {
            let want = flash::identity_of_elf(elf, HASH_PREFIX_LEN)?;
            let Capture::Identified(have) = &capture else {
                return Err(format!(
                    "board {} printed no identity, so it cannot be confirmed to run {want}",
                    target.board.id
                ));
            };
            if !want.matched_by(have) {
                return Err(format!(
                    "board {} is NOT running {}:\n  board: {have}\n  image: {want}\n\
                     Refusing to measure firmware that is not the firmware under test.",
                    target.board.id,
                    elf.display()
                ));
            }
            println!("m5stack-hil: board runs {have} (matches {})", elf.display());
        }

        if let Some(elf) = &cli.ensure_image {
            match flash::ensure_image(
                &mut l,
                &target.board,
                &target.flash,
                elf,
                &capture,
                target.banner.as_deref(),
                HASH_PREFIX_LEN,
            )? {
                Ensured::AlreadyCurrent(id) => println!("m5stack-hil: board already runs {id} — skipping flash"),
                Ensured::Flashed { why, now } => {
                    println!("m5stack-hil: flashed — {why}");
                    println!("m5stack-hil: verified {now}");
                }
            }
        }
    }

    if let Some(marker) = &cli.await_boot {
        let line = flash::await_marker(&mut l, marker, Duration::from_secs(30))
            .map_err(|m| format!("board {}: {m}\nTranscript: {}", target.board.id, cap.display()))?;
        println!("m5stack-hil: board up — {line}");
    }

    if let Some(secs) = cli.capture.map(Duration::from_secs) {
        let until = cli.until.as_deref().unwrap_or(NEVER);
        note(quiet, &format!("m5stack-hil: capturing for {secs:?}"));
        match l.wait_for_line(until, secs) {
            Outcome::Matched(line) => println!("m5stack-hil: matched — {line}"),
            Outcome::DeadlineExpired if cli.until.is_some() => {
                return Err(format!("never printed {until:?} within {secs:?}.\nTranscript: {}", cap.display()));
            }
            // No `--until`: the deadline IS the end of the capture, not a failure.
            Outcome::DeadlineExpired => {}
            Outcome::SourceFailed(m) => return Err(format!("{}: {m}", target.board.port)),
        }
        // A capture that lost bytes must say so — statistics or eyeballs over a
        // holed transcript are conclusions drawn from evidence that is missing
        // exactly where it matters.
        board::no_holes(&l, "during the capture")?;
        println!("m5stack-hil: captured {} lines -> {}", l.lines().len(), cap.display());
    }

    Ok(())
}

/// The command line is a contract, so it is tested like one.
///
/// These are the rules that used to live as `if` chains inside the parser and
/// were therefore only as good as somebody remembering to write them. Two were
/// in fact missing, and one of the two "declarative" replacements silently did
/// not fire — `requires` does not apply when the required argument is in an
/// already-satisfied `required` group. Declaring a rule is not the same as
/// enforcing it, so each one is asserted here against the real parser.
#[cfg(test)]
mod cli {
    use clap::{CommandFactory, Parser as _};

    use super::Cli;

    /// clap's own consistency check: unknown ids in a group, duplicate flags,
    /// impossible requirements. It panics with the offending name, which is far
    /// better than discovering the same thing from a user's command line.
    #[test]
    fn the_definition_is_internally_consistent() {
        Cli::command().debug_assert();
    }

    fn parse(args: &[&str]) -> Result<Cli, clap::Error> {
        Cli::try_parse_from(std::iter::once("m5stack-hil").chain(args.iter().copied()))
    }

    #[test]
    fn a_board_must_be_addressed_somehow() {
        assert!(parse(&["--read-identity"]).is_err(), "no address must be refused");
    }

    /// Two addresses is ambiguous, and picking one silently would drive the
    /// wrong board.
    #[test]
    fn the_ways_of_addressing_a_board_are_exclusive() {
        assert!(parse(&["--board", "b", "--mac", "AA:BB", "--read-identity"]).is_err());
        assert!(parse(&["--mac", "AA:BB", "--port", "/dev/x", "--id", "i", "--read-identity"]).is_err());
    }

    /// A lock keyed to a tty index would let two runs claim one board under two
    /// names, so a raw port has to bring its own stable id.
    #[test]
    fn a_port_cannot_be_used_without_a_stable_id() {
        assert!(parse(&["--port", "/dev/ttyX", "--read-identity"]).is_err());
        assert!(parse(&["--port", "/dev/ttyX", "--id", "rig-1", "--read-identity"]).is_ok());
    }

    /// Otherwise the tool claims a board, resets it, and exits having proved
    /// nothing — which reads like a pass.
    #[test]
    fn at_least_one_action_is_required() {
        assert!(parse(&["--board", "b"]).is_err());
        assert!(parse(&["--board", "b", "--capture", "5"]).is_ok());
    }

    /// THE rule that was silently ignored before, and then silently ignored
    /// again by a `requires` that does not fire inside a satisfied group. A rig
    /// selects between config entries, so it means nothing without a lookup.
    #[test]
    fn a_rig_or_config_is_refused_when_no_config_will_be_consulted() {
        assert!(parse(&["--rig", "bench", "--mac", "AA:BB", "--read-identity"]).is_err(), "--rig needs --board");
        assert!(parse(&["--config", "h.toml", "--mac", "AA:BB", "--read-identity"]).is_err(), "--config needs --board");
        assert!(parse(&["--rig", "bench", "--board", "b", "--read-identity"]).is_ok());
    }

    /// `--until` bounds a capture; on its own it was accepted and dropped.
    #[test]
    fn until_is_refused_without_a_capture_to_bound() {
        assert!(parse(&["--board", "b", "--read-identity", "--until", "done"]).is_err());
        assert!(parse(&["--board", "b", "--capture", "5", "--until", "done"]).is_ok());
    }

    /// A misspelled flag must stop the run. The hand-written parser did get
    /// this right; it is asserted so a later `allow_hyphen_values`-style
    /// loosening cannot take it away quietly.
    #[test]
    fn an_unknown_flag_is_refused_rather_than_ignored() {
        assert!(parse(&["--board", "b", "--read-identity", "--captrue", "5"]).is_err());
    }

    #[test]
    fn a_non_numeric_baud_is_refused() {
        assert!(parse(&["--board", "b", "--read-identity", "--baud", "fast"]).is_err());
    }
}
